### PR TITLE
I've made AUR package for yadm

### PR DESCRIPTION
**Pull request by kosciak9**
So I've updated README to reflect it. Look into it :)

### CODE REVIEW

**Comment by TheLocehiliosan** [comment]
Cool. I'll merge this change in. I don't use Arch Linux, but I assume this works. Looking at the PKGBUILD, seems to only install the program. Is it possible to update it so the yadm.1 manpage is included?

**Comment by kosciak9** [comment]
yes of course. I just followed 'others' section in the README. I will include it and pull another request.

**Comment by kosciak9** [comment]
just fyi, added this :)

**Comment by TheLocehiliosan** [comment]
That's fantastic!

**Comment by Zaplanincan** [comment]
Just install it from AUR this morning without problems, using it and like it very much... Thanks for that.

**Comment by kosciak9** [comment]
Loving to hear that :)

-----Original Message-----

**Pull request merged**
