### PR TITLE
Add `enter` function for easier interaction with git repo.

### PR DESCRIPTION
**Pull request by renard**
Run a subshell with all git variables set. This can be used to easily
interact with your git repository. This is also useful if you are using
Emacs Tramp and magit to manage your directory.

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

### CODE REVIEW

**Comment by TheLocehiliosan** [comment]
I think it is proper set the prompt of any sub-shell. This makes it clear to any user that they have entered a sub-shell. Can you take a look at the `set-prompts` branch I created (28a53648e4c86166a1e06d7b8ee439b21cdfae5a) and see if this works for you? I'm not familiar with your specific use-case, and I'm not familiar at all with Emacs.

**Comment by renard** [comment]
For what I tested it worked nicely here.

Thanks.

**Comment by TheLocehiliosan** [comment]
Yes, I like that suggestion. `\w` doesn't work for `zsh` though (I think you use `bash` like myself). I came up with this (3ff4778a5b4a30e9545d4fa59f9a392191f48b8f), now the tip of the `set-prompts` branch. Can you confirm it works for you?

**Comment by renard** [comment]
Seems you be good.

Thanks for the reactivity!

**Pull request merged**
