### PR TITLE
implement fish autocomplete

### PR DESCRIPTION
**Pull request by soraxas**
### What does this PR do?

Implement fish shell autocomplete

### Previous Behavior

Fish shell had no autocomplete script

### New Behavior

Fish shell now has autocomplete script!

### Have tests been written for this change?                                                                                                                                                                 

No

### Have these commits been signed with GnuPG?                                                                                                                                                               

Yes

### CODE REVIEW

**Comment by TheLocehiliosan** [comment]
@soraxas Thanks for this contribution... is this work finished? or can I change this to a *draft* PR for now? (looks like there were still some changes rolling in)

**Comment by soraxas** [comment]
Hi @TheLocehiliosan the work is finished, the second commit is only to add yadm's universal options (like `--yadm-dir`) which I missed, and I reorganized the commands a bit for clarity.

Sorry about the force-pushed, both times I forgot to sign with GnuPG and immediately signed them.

**Comment by TheLocehiliosan** [comment]
@soraxas - Would you be willing to add a third section for fish to `completion/README.md`? Perhaps just the manual instructions? I'll probably look into updating the homebrew formula to support fish completions when I do the next release.

**Comment by soraxas** [comment]
No problem! For your information, system-wise install will place completion file at `usr/share/fish/completions/` while use can place their own completion file at `$HOME/.config/fish/completions/`

**Comment by ian-h-chamberlain** [comment]
Hi @soraxas , I stumbled across this as I recently created my own (less polished) completions for `yadm`.

One suggestion I have is to use `yadm enter` for git completions, e.g. instead of 
```fish
# wraps git's autocomplete
set -l GIT_DIR (yadm introspect repo)
# setup the correct git-dir by appending it to git's argunment
complete -c yadm -w "git --git-dir=$GIT_DIR" 
```
use 
```fish
# wraps git's autocomplete
complete -c yadm -w "yadm enter git"
```
This has the advantage of setting `GIT_WORK_TREE` plus should continue to work if the implementation of `yadm enter` changes.

I have some other potential changes in mind to improve `yadm config` and `yadm gitconfig` completions, but I will wait for this to merge and post a separate PR for those :)

**Comment by TheLocehiliosan** [comment]
Thanks for the contribution. This has been merged into the develop branch.

**Pull request merged**
