### PR TITLE
Zsh completion

### PR DESCRIPTION
**Pull request by erijo**
### What does this PR do?

Updates the zsh completion to also complete all possible git commands.

### What issues does this PR fix or reference?

* #265
* #237 

### Previous Behavior

The completion for zsh only completes yadm commands.

### New Behavior

Now it completes yadm commands and all git commands. There's still some work to do, but the major features are there and should be usable.

### Have [tests][1] been written for this change?

No. Only manual testing.

### Have these commits been [signed with GnuPG][2]?

Yes

---

Please review [yadm's Contributing Guide][3] for best practices.

[1]: https://github.com/TheLocehiliosan/yadm/blob/master/.github/CONTRIBUTING.md#test-conventions
[2]: https://help.github.com/en/articles/signing-commits
[3]: https://github.com/TheLocehiliosan/yadm/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by TheLocehiliosan** [comment]
Thanks for digging into this. I will get this included before I release 3.0.0 (likely later today). I looked into home-brew's preferred ways to include completion for various shells, and will probably adopt  a re-org similar to #238.

**Comment by adigitoleo** [comment]
Hey, sorry I'm late with the testing, here is the one potential issue I have found:

1. ``cd`` into an existing git repo
2. type ``yadm add `` and press TAB

Before this patch this would complete the files inside the repo folder. After the patch, I get ``yadm add ./`` and pressing TAB again does not cycle through files. I think it only happens in folders that are git repos themselves.

**Comment by adigitoleo** [comment]
On further thought, I guess there would probably be other issues with tracking files in git and yadm at the same time (I don't actually do this, it's just some quirk I noticed), so maybe this is just "undefined" behaviour and we can leave it at that. I think "fixing" it (however that would look) is not trivial since the git autocomplete can't tell which working tree to use. I might check how this is handled in bash, but unless there are ither ideas I will close #265, since it works for normal directories.

**Comment by erijo** [comment]
@adigitoleo: I tried your use-case and it works for me. If I go to `~/source/yadm` and press TAB after entering `yadm add ` I get all files in the current directory as suggestions. But it doesn't work if I have `/source/` in `~/.gitignore` (which I usually have). Could it be something similar for you, i.e. that you have ignored the existing git repo? If not, what version of git and zsh are you using?

**Comment by adigitoleo** [comment]
@erijo: I tried again and it seems to be working now... in various local git repo clones... huh. Not sure what happened before, maybe it was due to gitignore rules as you suggest. Sorry for the false alarm, and thanks for taking the time to work on this.

**Pull request merged**
